In [1]:
import numpy as np

In [3]:
numbers = np.array([10,20,30,40,50])
data = np.array([
	[10,20,30,40,50],
	[60,70,80,90,100]
])


In [9]:
print(np.zeros(5))
print(np.full(5,7))

[0. 0. 0. 0. 0.]
[7 7 7 7 7]


In [4]:
print(np.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]


In [5]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [7]:
print(data.ndim)
print(data.shape)
print(data.size)
print(data.dtype)

2
(2, 5)
10
int64


In [11]:
print(numbers[1:4])
print(numbers[::2])
print(numbers[:])

[20 30 40]
[10 30 50]
[10 20 30 40 50]


In [9]:
print(data[0,1])
print(data[1,-1])

20
100


In [10]:
print(data[0,:])
print(data[:,1])

[10 20 30 40 50]
[20 70]


In [13]:
data[0,:]=0
print(data)

[[  0   0   0   0   0]
 [ 60  70  80  90 100]]


In [3]:
print(np.exp(np.array([0,1,2])))

[1.         2.71828183 7.3890561 ]


In [5]:
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [6]:
print(np.abs(np.array([-10,-5,0,5,10])))

[10  5  0  5 10]
