In [2]:
import numpy as np

In [10]:
numbers = np.array([10,20,30,40,50])
data = np.array((
    [1,2,3],
    [4,5,6]
))
data[1,2]=5
print(data[1,2])

5


In [9]:
print(np.zeros(5))
print(np.full(5,7))

[0. 0. 0. 0. 0.]
[7 7 7 7 7]


In [12]:
print(np.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]


In [15]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [5]:
print(data.shape)

(2, 3)
